module "rds" {
  source                         = "../../../modules/rds"
  allow_db_major_version_upgrade = "false"
  allow_db_minor_version_upgrade = "false"
  aws_region                     = "ca-central-1"
  db_engine                      = "postgres"
  db_engine_version              = "16.3"
  db_instance_class              = "db.t3.micro"
  db_port_number                 = "5432"
  db_storage_amount_gb           = "10"
  db_subnet_group_name           = "rds_instance"
  db_subnet_id_az1               = "subnet-025b04a95fb8c9424"
  db_subnet_id_az2               = "subnet-0418350375b4d9ac4"
  rds_db_credentials_secret_arn  = "arn:aws:secretsmanager:ca-central-1:715788907281:secret:rds_credentials-PGtdZI"
  security_group_name            = "rds_instance"
  vpc_cidr                       = "10.0.0.0/16"
  vpc_identifier                 = "vpc-0139b19677144f19a"
}